#
# EcoBosses
# by Auxilor
#

discover-recipes: true
log-spawn-kill: true

autospawn:
  one-boss-per-world: true # If only one boss can auto-spawn per world at once.

cooldown:
  in-actionbar: true
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: 0.5

cannot-afford:
  in-actionbar: true
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: 0.5

cannot-afford-type:
  in-actionbar: true
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: 0.5

cannot-afford-price:
  in-actionbar: true
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: 0.5

point-names: # If you have point names that look ugly (e.g. souls) then you can map them to nice names to be shown to players.
  example_point: "Nicely Formatted Point"

use-faster-move-trigger: true # Disable if you want move trigger to detect sub-1-block movements
raytrace-distance: 80 # The distance that alt_click should check for a location

potions:
  icon:
    permanent: true
    triggered: true
  ambient:
    permanent: false
    triggered: true
  particles:
    permanent: false
    triggered: true